"""Add non negative constraint to inventory quantity

Revision ID: 138dc6548b00
Revises: 5e8143b7e46f
Create Date: 2026-02-21 17:46:07.007881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '138dc6548b00'
down_revision: Union[str, Sequence[str], None] = '5e8143b7e46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
