"""Add core Sprout database models

Revision ID: 41706f35c7e1
Revises: 6dd7d1218a8f
Create Date: 2026-02-21 17:23:31.053351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41706f35c7e1'
down_revision: Union[str, Sequence[str], None] = '6dd7d1218a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commoditypricing',
    sa.Column('crop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commoditypricing_county'), 'commoditypricing', ['county'], unique=False)
    op.create_index(op.f('ix_commoditypricing_crop_name'), 'commoditypricing', ['crop_name'], unique=False)
    op.create_index(op.f('ix_commoditypricing_date'), 'commoditypricing', ['date'], unique=False)
    op.create_table('farminventory',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farminventory_crop_name'), 'farminventory', ['crop_name'], unique=False)
    op.create_index(op.f('ix_farminventory_farm_id'), 'farminventory', ['farm_id'], unique=False)
    op.create_table('outreachemail',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restaurant_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('drafted', 'sent', 'opened', 'replied', 'converted', name='outreachstatus_enum'), nullable=True),
    sa.Column('draft_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('menu_keywords_matched', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreachemail_farm_id'), 'outreachemail', ['farm_id'], unique=False)
    op.create_table('transaction',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_crop_name'), 'transaction', ['crop_name'], unique=False)
    op.create_index(op.f('ix_transaction_farm_id'), 'transaction', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_farm_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_crop_name'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_outreachemail_farm_id'), table_name='outreachemail')
    op.drop_table('outreachemail')
    op.execute('DROP TYPE IF EXISTS outreachstatus_enum')
    op.drop_index(op.f('ix_farminventory_farm_id'), table_name='farminventory')
    op.drop_index(op.f('ix_farminventory_crop_name'), table_name='farminventory')
    op.drop_table('farminventory')
    op.drop_index(op.f('ix_commoditypricing_date'), table_name='commoditypricing')
    op.drop_index(op.f('ix_commoditypricing_crop_name'), table_name='commoditypricing')
    op.drop_index(op.f('ix_commoditypricing_county'), table_name='commoditypricing')
    op.drop_table('commoditypricing')
    # ### end Alembic commands ###
