"""Add validations and constraints to models

Revision ID: 4f7b075fa9a7
Revises: 138dc6548b00
Create Date: 2026-02-21 17:50:06.655002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f7b075fa9a7'
down_revision: Union[str, Sequence[str], None] = '138dc6548b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_commodity_pricing', 'commoditypricing', ['crop_name', 'county', 'date'])
    op.create_unique_constraint('uq_farm_inventory_crop', 'farminventory', ['farm_id', 'crop_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_farm_inventory_crop', 'farminventory', type_='unique')
    op.drop_constraint('uq_commodity_pricing', 'commoditypricing', type_='unique')
    # ### end Alembic commands ###
