"""Add Farm model

Revision ID: 6dd7d1218a8f
Revises: 15383e2a714d
Create Date: 2026-02-21 11:43:13.774254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dd7d1218a8f'
down_revision: Union[str, Sequence[str], None] = '15383e2a714d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('farm_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_places_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digital_health_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_farm_name'), 'farm', ['farm_name'], unique=False)
    op.create_index(op.f('ix_farm_location_state'), 'farm', ['location_state'], unique=False)
    op.create_index(op.f('ix_farm_location_zip'), 'farm', ['location_zip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_location_zip'), table_name='farm')
    op.drop_index(op.f('ix_farm_location_state'), table_name='farm')
    op.drop_index(op.f('ix_farm_farm_name'), table_name='farm')
    op.drop_table('farm')
    # ### end Alembic commands ###
