"""add email fields to outreach

Revision ID: d41a7ab478dd
Revises: 4f7b075fa9a7
Create Date: 2026-02-21 16:14:33.199891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd41a7ab478dd'
down_revision: Union[str, Sequence[str], None] = '4f7b075fa9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreachemail', sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('outreachemail', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('outreachemail', sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('outreachemail', 'draft_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreachemail', sa.Column('draft_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('outreachemail', 'body')
    op.drop_column('outreachemail', 'subject')
    op.drop_column('outreachemail', 'recipient_email')
    # ### end Alembic commands ###
